import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Header } from '@/Widgets/Header';
import { Footer } from '@/Widgets/Footer';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
  children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header/>
                {children}
                <Footer/>
            </body>
        </html>
    );
}
